build
	1. Download typesense-server
	2. nodejs/npm + sveltekit
	3. publish
:wq

FROM python:3.11-alpine as builder
ADD .. /s
RUN apk add binutils && \
    python -m pip install -U pip && 
    python -m pip install -r /s/requirements.txt

WORKDIR /app
ADD . /app
RUN python -m PyInstaller -F dhcpleases.py --add-data=pywebsvc/static/:pywebsvc/static && \
    ls -R dist && \
    dist/dhcpleases --help

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/dist/dhcpleases /app/dhcpleases
ENTRYPOINT ["/app/dhcpleases", "--web"]
