version: "3"
services:
  papertrail:
    #image: ghcr.io/ankurvdev/papertrail:main
    build: .
    container_name: papertrail
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./test:/cache:Z
      - ./docs:/data:Z
