[build-system]
requires = ["setuptools"]

[project]
name = "papertrail"
dynamic = ["version"]
description = "PaperTrail Document management system"

[tool.black]
line-length = 140

[tool.ruff]
line-length = 140
fixable = ["ALL"]
select = ["I", "E", "PL", "F", "PTH"]
ignore = []
