trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    jobs:
      - job:
        steps:
          - script: python ci/run.py container-build --export=image.tar
          - publish: image.tar
            artifact: image

  - stage:
    jobs:
      - job:
        steps:
          - download: current
            artifact: image
          - script: python ci/run.py container-test --import=$(Pipeline.Workspace)/image/image.tar
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: cache
              ArtifactName: test-output
              StoreAsTar: true


