trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    jobs:
      - job:
        steps:
          - script: ci/run.sh build image.tar
          - publish: image.tar
            artifact: image

  - stage:
    jobs:
      - job:
        steps:
          - download: current
            artifact: image
          - script: ci/run.sh test $(Pipeline.Workspace)/image/image.tar
          - publish: cache
            artifact: test-output


